export const CREATE_REVIEW_RAING_REQUEST = "CREATE_REVIEW_RATING_REQUEST";
export const CREATE_REVIEW_RATING_SUCCESS = "CREATE_REVIEW_RATING_SUCCESS";
export const CREATE_REVIEW_RATING_FAILUER = "CREATE_REVIEW_RATING_FAILURE";

export const GET_REVIEW_RATING_REQUEST = "GET_REVIEW_RATING_REQUEST";
export const GET_REVIEW_RATING_SUCCESS = "GET_REVIEW_RATING_SUCCESS";
export const GET_REVIEW_RATING_FAILUER = "GET_REVIEW_RATING_FAILURE";

